"""Initial schema without teams

Revision ID: 6f9556a96b4f
Revises: 
Create Date: 2026-01-25 17:31:47.606550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9556a96b4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opponent_name', sa.String(length=100), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('source_sheet', sa.String(length=100), nullable=False),
    sa.Column('import_batch_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scoring_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('player_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('puesto', sa.Integer(), nullable=False),
    sa.Column('tiempo_juego', sa.Float(), nullable=False),
    sa.Column('tackles_positivos', sa.Integer(), nullable=False),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('tackles_errados', sa.Integer(), nullable=False),
    sa.Column('portador', sa.Integer(), nullable=False),
    sa.Column('ruck_ofensivos', sa.Integer(), nullable=False),
    sa.Column('pases', sa.Integer(), nullable=False),
    sa.Column('pases_malos', sa.Integer(), nullable=False),
    sa.Column('perdidas', sa.Integer(), nullable=False),
    sa.Column('recuperaciones', sa.Integer(), nullable=False),
    sa.Column('gana_contacto', sa.Integer(), nullable=False),
    sa.Column('quiebres', sa.Integer(), nullable=False),
    sa.Column('penales', sa.Integer(), nullable=False),
    sa.Column('juego_pie', sa.Integer(), nullable=False),
    sa.Column('recepcion_aire_buena', sa.Integer(), nullable=False),
    sa.Column('recepcion_aire_mala', sa.Integer(), nullable=False),
    sa.Column('try', sa.Integer(), nullable=False),
    sa.Column('score_absoluto', sa.Float(), nullable=True),
    sa.Column('puntuacion_final', sa.Float(), nullable=True),
    sa.Column('scoring_config_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['scoring_config_id'], ['scoring_configurations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'match_id', name='uq_player_match')
    )
    op.create_table('scoring_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('action_name', sa.String(length=50), nullable=False),
    sa.Column('forwards_weight', sa.Float(), nullable=False),
    sa.Column('backs_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['scoring_configurations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id', 'action_name', name='uq_config_action')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoring_weights')
    op.drop_table('player_match_stats')
    op.drop_table('scoring_configurations')
    op.drop_table('players')
    op.drop_table('matches')
    # ### end Alembic commands ###
