"""Add match metadata fields

Revision ID: e530b49e113f
Revises: 6f9556a96b4f
Create Date: 2026-01-25 18:11:36.053633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e530b49e113f'
down_revision: Union[str, None] = '6f9556a96b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('location', sa.String(length=20), nullable=True))
    op.add_column('matches', sa.Column('result', sa.String(length=20), nullable=True))
    op.add_column('matches', sa.Column('our_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('opponent_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'opponent_score')
    op.drop_column('matches', 'our_score')
    op.drop_column('matches', 'result')
    op.drop_column('matches', 'location')
    # ### end Alembic commands ###
